### ISSUE TITLE
Include it to SpamAssassin?

### ISSUE THREAD

**Issue by catap** [bigio/spamassassin-esp#12]
Good day!

I just discovered this plugin... and before I create a package for used system I'd like to ask: do you plan to contribute it to SpamAssassin?

If yes and soon, I'll live without package, but otherwise I think it migth be usefull.

**Comment by bigio** [comment]
I have committed the plugin to SpamAssassin but then we decided to remove it because it might need frequent changes.
If you want to use the rbl you only need "Esp-rbl.cf" file and SpamAssassin 4.x, if you have your own data you must use the plugin.
I maintain the rbl, happy to receive ESP ids to add to the rbl.

**Comment by catap** [comment]
Thanks, indeed, it seems that package no need at all.
